### ISSUE TITLE
template class content doesn't work.

### ISSUE THREAD

**Issue by kurodz** [voronianski/jquery.avgrund.js#65]
<div class="content" style="display: none;">
    My content for popin!
</div>

$('element').avgrund({
    template: $(".content")
});

When I click element i set , It pop up but nothing in there.

and I remove style="display:none;" , it works but The default page will show the content .

**Comment by imtiyaz4410** [comment]
> Hi
> I have same problem, I add one code in jquery.avgrund.js after $('.avgrund-popin').css({...}) at line 93
> 
> //add to show template.selector//
> $(template.selector).show();
> 
> And it can work,

This Is Not Right Way To Handle It You Have To Create A New Div With class="avgrund-overlay" 



<div class="avgrund-overlay">

	<div class="content" >
		My content for popin!
</div></div>
