### ISSUE TITLE
How to close avgrund element use javascript function?

### ISSUE THREAD

**Issue by mutoe** [voronianski/jquery.avgrund.js#71]
just like `$("#model-login").avgrund().deactivate();` , but this script is error. What should I do?

**Comment by LordFirst** [comment]
Hi, I have not found how to use the deactivate() function, but after looking at the source code I managed to close the popin using this code (used in the deactivate() function) :

<pre>$('body').removeClass('avgrund-active');
setTimeout(function() {
     $('.avgrund-popin').remove();
}, 500);</pre>
